sudo: false
language: php
php:
   - 5.6

cache:
  directories:
   - $HOME/download-cache
install:
  - curl -sS https://getcomposer.org/installer | php
  #install dependencies
  - php composer.phar install --dev

before_script:
   - mkdir -p $HOME/download-cache
   - export SOLR_VERSION="5.5.0"
   - export SOLR_PORT="8180"
   - bash ./solr5-install.sh
   - export SOLR_CORENAME="cbtest_test"
   - export SOLR_CONFIGSET="/server/solr/configsets/default_configs/conf"
   - bash ./solr5-addcore.sh

script:
   - vendor/bin/phpunit Test.php

after_script:
   - bash ./solr5-stop.sh
